### ISSUE TITLE
Store results of optimization in system not in Substrate

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/ContactMechanics#38]
At least that's what we decided for the Adhesion potentials in Adhesion. 

Example: 
https://github.com/ContactEngineering/ContactMechanics/blob/47c100be6eef46711db70bcd6d15c1abba672277/ContactMechanics/Systems.py#L863

@pastewka what do you think ?

**Comment by pastewka** [comment]
Sounds good - I think this should go into system

**Comment by pastewka** [comment]
I think this is already the case and the line is a bug. `substrate.force` should contain just the force contribution from the substrate, `self.force` should contain the sum of substrate plus interaction.

**Comment by sannant** [comment]
I disagree. when I call system.force I expect to get the physical value I am interested in (either the substrate force or the interaction force), not the residual of the optimization problem. 

Happy to create a variable called residual_force

**Comment by sannant** [comment]
I want to additionally point out that: 

- we made the code-style decision not to store internal states in the interaction potentials, and for consistency I we should not store any force in the substrate. 
- If we change our mind and want to store a force in the substrate, this line is not a bug. In the context of dual minimization without adhesion, result.x is exactly the force applied on the substrate.
