### ISSUE TITLE
Problem while installing ContactMechanics

### ISSUE THREAD

**Issue by hans-td** [ContactEngineering/ContactMechanics#46]
Hello developers, 
I am trying to install ContactMechanics. I work on Ubuntu 20.10, and I have Python 3 and FFTW3 installed. However, installation fails when I install the dependencies (as specified in the documentation under 'Installation'). 
Installation of MuFFT and SurfaceTopography fail. 
I include the errors in a separate text file. [error_message.txt](https://github.com/ContactEngineering/ContactMechanics/files/7482413/error_message.txt)
I already tried the advices written in the documentation (regarding FFTW3 path, and LAPACK and OPENBLAS), with no effect. 
I would be happy if you could provide me with any pointers on what could be the issue. 

Hans

**Comment by AntoineSIMTEK** [comment]
Dear Hans, 

I think what is missing is netCDF.
The easiest way to get it is through the apt-get if that is an option for you. 
For an example of installation on Ubuntu, you can have a look on our singularity containers:
https://github.com/ContactEngineering/SurfaceTopography/blob/master/singularity/SurfaceTopography_serial.def

**Comment by pastewka** [comment]
@hans-td  did this solve your problem?

**Comment by AntoineSIMTEK** [comment]
You are welcome ! I will update the installation instructions.

**Comment by AntoineSIMTEK** [comment]
Closed by https://github.com/ContactEngineering/ContactMechanics/commit/26fe38be5115718de9bbb326679c345cf0202deb
